version: '3.9'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    volumes:
      - /home/oryadi/vol/back:/backend_app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - '3000:3000'
    volumes:
      - /home/oryadi/vol/front:/frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - react_app_network

networks:
  react_app_network:

